### ISSUE TITLE
no JCublas-10.0.0-linux-x86_64 in java.library.path

### ISSUE THREAD

**Issue by PerkzZheng** [KarmaGYZ/flink-mnist#1]
Hi, 
I am getting issues shown below after following the steps and do the image processing. 

ENV:
`cuda 10.0.0, java 1.8, flink 1.11.2`
`jcublas-natives-10.0.0-linux-x86_64.jar` is in `/flink/lib/`

```java
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no JCublas-10.0.0-linux-x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at jcuda.LibUtils.loadLibrary(LibUtils.java:143)
        at jcuda.jcublas.JCublas.initialize(JCublas.java:96)
        at jcuda.jcublas.JCublas.<clinit>(JCublas.java:81)
        at org.apache.flink.MNISTClassifier.close(MNISTClassifier.java:124)
        at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:729)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUpInvoke(StreamTask.java:645)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:549)
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
        at java.base/java.lang.Thread.run(Thread.java:834)
Stack trace from the attempt to load the library as a resource:
java.lang.UnsatisfiedLinkError: /tmp/jcuda-5eb2ad65-96ed-4294-bd2c-df8510969d3c/jcuda-03b66d1f-f0d4-451a-9e2b-5ac246f71546/jcuda-38ece566-1372-43f8-80fb-5087bec45662/jcuda-6f53293e-6b62-4fcb-becc-dd14575d2acf/jcuda-5e28b27a-5ae4-4989-969b-056a4e7bbc79/jcuda-35d62953-8139-4997-9059-5f445f573169/jcuda-c52bf5b2-1389-476e-8a5b-806b9a96ee99/jcuda-47b1800c-a9e7-405e-90ec-0d5badd81405/jcuda-dba3d783-7c95-4648-90c5-6098b9943c05/jcuda-5e6f2b57-d3d8-4dd7-b0a7-be128f5df924/jcuda-05625a43-bf6e-48fa-8b60-ceb4b459e922/libJCublas-10.0.0-linux-x86_64.so: libcublas.so.10.0: cannot open shared object file: No such file or directory      
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at jcuda.LibUtils.loadLibraryResource(LibUtils.java:260)
        at jcuda.LibUtils.loadLibrary(LibUtils.java:158)
        at jcuda.jcublas.JCublas.initialize(JCublas.java:96)
        at jcuda.jcublas.JCublas.<clinit>(JCublas.java:81)
        at org.apache.flink.MNISTClassifier.close(MNISTClassifier.java:124)
        at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:729)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUpInvoke(StreamTask.java:645)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:549)
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
        at java.base/java.lang.Thread.run(Thread.java:834)
---(end of nested stack traces)---

                at jcuda.LibUtils.loadLibrary(LibUtils.java:193)
                at jcuda.jcublas.JCublas.initialize(JCublas.java:96)
                at jcuda.jcublas.JCublas.<clinit>(JCublas.java:81)
                at org.apache.flink.MNISTClassifier.close(MNISTClassifier.java:124)
                at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
                at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
                at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:729)
                at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUpInvoke(StreamTask.java:645)
                at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:549)
                ... 3 more
```

**Comment by KarmaGYZ** [comment]
Does the jcuda-natives-10.0.0-linux-x86_64.jar also in `/flink/lib/`?

**Comment by PerkzZheng** [comment]
@KarmaGYZ yes. both are in `/flink/lib/`

**Comment by PerkzZheng** [comment]
```shell
perkz@bfs:/data/perkz/flink/lib$ jar -tf jcublas-natives-10.0.0-linux-x86_64.jar  
META-INF/MANIFEST.MF 
META-INF/
lib/
META-INF/maven/ 
META-INF/maven/org.jcuda/
META-INF/maven/org.jcuda/jcublas-natives/
lib/libJCublas-10.0.0-linux-x86_64.so
lib/libJCublas2-10.0.0-linux-x86_64.so
META-INF/maven/org.jcuda/jcublas-natives/pom.xml
META-INF/maven/org.jcuda/jcublas-natives/pom.properties
```

```shell
perkz@bfs:/data/perkz/flink/lib$ jar -tf jcuda-natives-10.0.0-linux-x86_64.jar  
META-INF/MANIFEST.MF 
META-INF/
lib/
META-INF/maven/
META-INF/maven/org.jcuda/
META-INF/maven/org.jcuda/jcuda-natives/
lib/libJCudaDriver-10.0.0-linux-x86_64.so
lib/libJNvrtc-10.0.0-linux-x86_64.so
lib/libJCudaRuntime-10.0.0-linux-x86_64.so
META-INF/maven/org.jcuda/jcuda-natives/pom.xml
META-INF/maven/org.jcuda/jcuda-natives/pom.properties
```

**Comment by KarmaGYZ** [comment]
@PerkzZheng why does the `JCublas` initiated at the `MNISTClassifier.close`? Would you like to share the jm and tm log here?

**Comment by PerkzZheng** [comment]
@KarmaGYZ Sorry for replying so late. I am working on setting up everything again. And it works now, it could be some version problems.  Thanks for your time.

Finally, I got results in `flink-perkz-taskexecutor-2-bfs.out`. 
```
7
2
1
0
4
1
4
9
....
```
However, --output seems not working, when I set it, I only got an empty directory like `2020-10-29--15`

**Comment by KarmaGYZ** [comment]
Would you like to share all the log files in the `/flink/log/` directory?

**Comment by PerkzZheng** [comment]
Appreciate it.
[Flink-logs.zip](https://github.com/KarmaGYZ/flink-mnist/files/5456857/Flink-logs.zip)

**Comment by KarmaGYZ** [comment]
As the javaDoc says, the output path is the base path where all the buckets are going to be created as sub-directories. In your logs, it seems the parameter is invalid and the job is actually failed because it could not create "/2020-10-29--15" directory.

**Comment by PerkzZheng** [comment]
It is previous testing. I use valid directory under my current directory, and it still gets a empty directory. 
So, the flink-perkz-taskexecutor-2-bfs.out is a valid output ?

**Comment by PerkzZheng** [comment]
[Flink-log-1.zip](https://github.com/KarmaGYZ/flink-mnist/files/5456918/Flink-log-1.zip)
Sorry for the previous testing. I start over to make sure everything relates to one recent test.  Please check it.

**Comment by KarmaGYZ** [comment]
The flink-perkz-taskexecutor-2-bfs.out is a valid output.

I could not find anything wrong in your logs. Not sure what happens.

**Comment by PerkzZheng** [comment]
Thanks for taking time. It is great to see that flink enables gpu awareness.

**Comment by KarmaGYZ** [comment]
Hi, @PerkzZheng . After a deep investigation, I find it is a valid issue. The root cause is the `StreamingFileSink` require to open the checkpoint. The latest commit fixes that issue.

**Comment by PerkzZheng** [comment]
> Hi, @PerkzZheng . After a deep investigation, I find it is a valid issue. The root cause is the `StreamingFileSink` require to open the checkpoint. The latest commit fixes that issue.

@KarmaGYZ Thanks for your investigation.
